apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route
  labels:
    component: httproute
spec:
  parentRefs:
  - name: gateway-api # Nome del gateway
  rules:
  - backendRefs:
    - name: nginx-svc # Nome del service di tipo ClusterIP
      port: 80