apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-backend
  labels:
    app: f1-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f1-backend
  template:
    metadata:
      labels:
        app: f1-backend
    spec:
      containers:
        - name: f1-backend
          image: gridops-backend:0.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000