apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - deployment.yaml
  - clusterip-svc.yaml
  - http-route.yaml
  - ghcr-credentials.sops.yaml