apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:F0xPu/KKfMt0AXW2/zLAIro5RwQz4RHv79yiHNe8iGxLu+WpnVsYbVo3kJH+MpaP1UIZDCaGReOgViThPB3MpYtSRLLcViqrcqbY/fmjIET2eQCHJo7Kue1fn7uw1ceCJRMJALKFpCv+cJq4IkirCmhfUT3UpAZjmMcid2bUoKodZKI3pEWDNJsp2rJOpPxAnwECGCTHhJtgJPHEXKgXag4TpGDS02oKTi0DvQH9nsAoXhQkHIhKIHZxg/F8YXON9XM61tKZMQbbHE8UL1Ie9SvrHsX51l1QXFFTCPrqtbSiOkXLb651klM5SGo=,iv:K9i1xNnAK77Y7YbA/P3rrQTlNDz0fp+b9LzYdmRFwy0=,tag:jCWIB2UTPpMO3EOXYKs75A==,type:str]
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1alwtn45p3ymhuuwl9tn6ddpxjfmx65x6emd7flkakne99tvs9q7qwuq3sx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZHp2YVJWd3BtcWdFYUpl
            THhxYkxsRUZjRi9qc3FCaG1IS0xjenJuWlhzCllqNk10dDF1cGlYYncvWjdwblRC
            NU43TEIzYVh2SmlZRWhXUmk4b0Zzc0UKLS0tIFdTV095OWpGV2o1b0RVdDlLcVY3
            MmRIQW9GbnZtc0ZTTkErRGlkNGxGRlUKVDRvcTAf+mfBHFiCuPoPA10FcckE1i8j
            oX8SmwztYu9c6IRy1muAsHsxIcmJrFFYgpeo1DgzX/H6eqYHLyrXXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T15:01:22Z"
    mac: ENC[AES256_GCM,data:4AkqA9eILbhnslFeNnJGG+4vYqQT3wlqCuj//bB8ThIE3QEUogjXe+yCdYwXxRRz83520nindKeNNiALzGRCHQk0i+J0tCLx6nn1D9RZkF2ceeAzE1Jyv8FPSrCQ2/1JPJ3ewhpbVqKK8/invjSSau588w1UX0chSa3t7NyEEXk=,iv:2ZTuSSy6YfMArz2mnvMRI/+GAvcamZkBUaorNOGxVvU=,tag:bXFSq86OIb7U2l9QVFFcDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
