apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k9s-project
  namespace: flux-system
spec:
  interval: 1m
  path: ./k9s_project
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  qqdecryption:
    provider: sops
    secretRef:
      name: sops-age