apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: gridops
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
    includeTemplates: true
  - pairs:
      app.kubernetes.io/name: gridops
      app.kubernetes.io/component: gitops-reconciliation
      app.kubernetes.io/part-of: gridops
    includeSelectors: true
