apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
data:
  values.yaml: |
    grafana:
      enabled: true
      adminPassword: admin

    kubeControllerManager:
      enabled: false

    kubeEtcd:
      enabled: false

    kubeProxy:
      enabled: false

    kubeScheduler:
      enabled: false

    prometheus:
      prometheusSpec:
        retention: 7d
        scrapeInterval: 30s

    alertmanager:
      enabled: true