apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-backend
  labels:
    app: f1-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f1-backend
  template:
    metadata:
      labels:
        app: f1-backend
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: f1-backend
          image: ghcr.io/ctrl-zzz/gridops:20260921-083816-40d813cc # {"$imagepolicy": "flux-system:gridops"}
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://opentelemetry-collector.monitoring.svc.cluster.local:4317"
          ports:
            - name: http
              containerPort: 8000
          # - name: metrics
          #   containerPort: 9090
